/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MedChain } from "./MedChain";
export * as factories from "./factories";
export { MedChain__factory } from "./factories/MedChain__factory";
