/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MedChain {
  export type AuditLogStruct = {
    accessor: AddressLike;
    recordId: BigNumberish;
    timestamp: BigNumberish;
    action: string;
  };

  export type AuditLogStructOutput = [
    accessor: string,
    recordId: bigint,
    timestamp: bigint,
    action: string
  ] & { accessor: string; recordId: bigint; timestamp: bigint; action: string };
}

export interface MedChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "auditTrails"
      | "checkAccess"
      | "createRecord"
      | "emergencyMode"
      | "getAuditTrail"
      | "getDoctorAccessibleRecords"
      | "getPatientRecordIds"
      | "getRecord"
      | "getStats"
      | "getUserInfo"
      | "grantAccess"
      | "patientRecords"
      | "permissions"
      | "recordCounter"
      | "records"
      | "registerUser"
      | "revokeAccess"
      | "toggleEmergencyMode"
      | "users"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "EmergencyModeToggled"
      | "RecordAccessed"
      | "RecordCreated"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "auditTrails",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAccess",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createRecord",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditTrail",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDoctorAccessibleRecords",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientRecordIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getUserInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "patientRecords",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "permissions",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleEmergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auditTrails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditTrail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDoctorAccessibleRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientRecordIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    patient: AddressLike,
    doctor: AddressLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    doctor: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    patient: string;
    doctor: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [patient: AddressLike, doctor: AddressLike];
  export type OutputTuple = [patient: string, doctor: string];
  export interface OutputObject {
    patient: string;
    doctor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyModeToggledEvent {
  export type InputTuple = [status: boolean];
  export type OutputTuple = [status: boolean];
  export interface OutputObject {
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordAccessedEvent {
  export type InputTuple = [accessor: AddressLike, recordId: BigNumberish];
  export type OutputTuple = [accessor: string, recordId: bigint];
  export interface OutputObject {
    accessor: string;
    recordId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordCreatedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    patient: AddressLike,
    recordType: string
  ];
  export type OutputTuple = [
    recordId: bigint,
    patient: string,
    recordType: string
  ];
  export interface OutputObject {
    recordId: bigint;
    patient: string;
    recordType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    userAddress: AddressLike,
    name: string,
    role: BigNumberish
  ];
  export type OutputTuple = [userAddress: string, name: string, role: bigint];
  export interface OutputObject {
    userAddress: string;
    name: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedChain extends BaseContract {
  connect(runner?: ContractRunner | null): MedChain;
  waitForDeployment(): Promise<this>;

  interface: MedChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  auditTrails: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        accessor: string;
        recordId: bigint;
        timestamp: bigint;
        action: string;
      }
    ],
    "view"
  >;

  checkAccess: TypedContractMethod<
    [_patient: AddressLike, _doctor: AddressLike],
    [
      [boolean, bigint, bigint, string] & {
        hasAccess: boolean;
        grantedAt: bigint;
        expiresAt: bigint;
        purpose: string;
      }
    ],
    "view"
  >;

  createRecord: TypedContractMethod<
    [_ipfsHash: string, _recordType: string, _description: string],
    [bigint],
    "nonpayable"
  >;

  emergencyMode: TypedContractMethod<[], [boolean], "view">;

  getAuditTrail: TypedContractMethod<
    [_user: AddressLike],
    [MedChain.AuditLogStructOutput[]],
    "view"
  >;

  getDoctorAccessibleRecords: TypedContractMethod<
    [_doctor: AddressLike],
    [bigint[]],
    "view"
  >;

  getPatientRecordIds: TypedContractMethod<
    [_patient: AddressLike],
    [bigint[]],
    "view"
  >;

  getRecord: TypedContractMethod<
    [_recordId: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        patient: string;
        ipfsHash: string;
        recordType: string;
        description: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [[bigint, boolean] & { totalRecords: bigint; emergencyStatus: boolean }],
    "view"
  >;

  getUserInfo: TypedContractMethod<
    [_userAddress: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        name: string;
        role: bigint;
        isRegistered: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [_doctor: AddressLike, _expiryDuration: BigNumberish, _purpose: string],
    [void],
    "nonpayable"
  >;

  patientRecords: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  permissions: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, bigint, bigint, boolean, string] & {
        doctorAddress: string;
        grantedAt: bigint;
        expiresAt: bigint;
        isActive: boolean;
        purpose: string;
      }
    ],
    "view"
  >;

  recordCounter: TypedContractMethod<[], [bigint], "view">;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        recordId: bigint;
        patientAddress: string;
        ipfsHash: string;
        recordType: string;
        description: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  registerUser: TypedContractMethod<
    [_name: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [_doctor: AddressLike],
    [void],
    "nonpayable"
  >;

  toggleEmergencyMode: TypedContractMethod<[], [void], "nonpayable">;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean, bigint] & {
        userAddress: string;
        name: string;
        role: bigint;
        isRegistered: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "auditTrails"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        accessor: string;
        recordId: bigint;
        timestamp: bigint;
        action: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkAccess"
  ): TypedContractMethod<
    [_patient: AddressLike, _doctor: AddressLike],
    [
      [boolean, bigint, bigint, string] & {
        hasAccess: boolean;
        grantedAt: bigint;
        expiresAt: bigint;
        purpose: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createRecord"
  ): TypedContractMethod<
    [_ipfsHash: string, _recordType: string, _description: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAuditTrail"
  ): TypedContractMethod<
    [_user: AddressLike],
    [MedChain.AuditLogStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDoctorAccessibleRecords"
  ): TypedContractMethod<[_doctor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPatientRecordIds"
  ): TypedContractMethod<[_patient: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [_recordId: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        patient: string;
        ipfsHash: string;
        recordType: string;
        description: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [[bigint, boolean] & { totalRecords: bigint; emergencyStatus: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserInfo"
  ): TypedContractMethod<
    [_userAddress: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        name: string;
        role: bigint;
        isRegistered: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [_doctor: AddressLike, _expiryDuration: BigNumberish, _purpose: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "patientRecords"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "permissions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, bigint, bigint, boolean, string] & {
        doctorAddress: string;
        grantedAt: bigint;
        expiresAt: bigint;
        isActive: boolean;
        purpose: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        recordId: bigint;
        patientAddress: string;
        ipfsHash: string;
        recordType: string;
        description: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [_name: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<[_doctor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleEmergencyMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean, bigint] & {
        userAddress: string;
        name: string;
        role: bigint;
        isRegistered: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyModeToggled"
  ): TypedContractEvent<
    EmergencyModeToggledEvent.InputTuple,
    EmergencyModeToggledEvent.OutputTuple,
    EmergencyModeToggledEvent.OutputObject
  >;
  getEvent(
    key: "RecordAccessed"
  ): TypedContractEvent<
    RecordAccessedEvent.InputTuple,
    RecordAccessedEvent.OutputTuple,
    RecordAccessedEvent.OutputObject
  >;
  getEvent(
    key: "RecordCreated"
  ): TypedContractEvent<
    RecordCreatedEvent.InputTuple,
    RecordCreatedEvent.OutputTuple,
    RecordCreatedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "AccessGranted(address,address,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(address,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "EmergencyModeToggled(bool)": TypedContractEvent<
      EmergencyModeToggledEvent.InputTuple,
      EmergencyModeToggledEvent.OutputTuple,
      EmergencyModeToggledEvent.OutputObject
    >;
    EmergencyModeToggled: TypedContractEvent<
      EmergencyModeToggledEvent.InputTuple,
      EmergencyModeToggledEvent.OutputTuple,
      EmergencyModeToggledEvent.OutputObject
    >;

    "RecordAccessed(address,uint256)": TypedContractEvent<
      RecordAccessedEvent.InputTuple,
      RecordAccessedEvent.OutputTuple,
      RecordAccessedEvent.OutputObject
    >;
    RecordAccessed: TypedContractEvent<
      RecordAccessedEvent.InputTuple,
      RecordAccessedEvent.OutputTuple,
      RecordAccessedEvent.OutputObject
    >;

    "RecordCreated(uint256,address,string)": TypedContractEvent<
      RecordCreatedEvent.InputTuple,
      RecordCreatedEvent.OutputTuple,
      RecordCreatedEvent.OutputObject
    >;
    RecordCreated: TypedContractEvent<
      RecordCreatedEvent.InputTuple,
      RecordCreatedEvent.OutputTuple,
      RecordCreatedEvent.OutputObject
    >;

    "UserRegistered(address,string,uint8)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
